version: 2

jobs:
  build:
    docker:
      # - image: gradle:7.4-jdk17      
      - image: cimg/android:2022.01

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      # # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "build.gradle" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      - run: ./gradlew androidDependencies

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test
      - run: gradle build
      - store_artifacts:
          path: app/build/output
          